[package]
name = "tarball-extraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4 = "1.23.2"
reqwest = "0.11.6"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
